### PR TITLE
Added icewm theme for installation

### PR DESCRIPTION
**Pull request by LelCP**
Based on preexisting theme and config from https://github.com/openSUSE/icewm-config-openSUSE

### CODE REVIEW

**Comment by LelCP** [comment]
Window during installation appeared orange https://openqa.opensuse.org/tests/625525#step/welcome/2

**Comment by DimStar77** [comment]
We fiscussed on IRC a few days ago: this belongs most likely rather to the yast-branding package, which has already icewem theme stuff for the installer

**Comment by LelCP** [comment]
There are multiple reasons why I don't want that:

- Installation theme for YaST-installation for openSUSE (as opposed to SLE), has been kept in this repository here for some time now (since 12 series from what I can tell)
- YaST-theme repository shouldn't exist:
  - icons and a lot of other elements belong to modules, not whole YaST
  - wmconfig belongs to distro's config, not upstream YaST (you treat it like it is just for SLE and openSUSE, believe that YaST one day could be ported somewhere else)
  - themes are matter of branding for particular release and distro, not for YaST's overall upstream appearance or overall distro appearance across all time
- Next generations will have much easier job adjusting parts of one repo to fit newer branding (as opposed to dealing with multiple repos, as this is small repo anyway)
- We already have parts that are used only during installation in this repo

**Comment by lnussel** [comment]
ok so that means /etc/icewm/preferences.yast2 has to be removed from yast2-branding-openSUSE?

Could you also take care of the spec file if we merge this?

**Comment by LelCP** [comment]
@lnussel not at all, it can stay there, it doesn't affect theme in any way :D 
Well, with exception of removing titlebar buttons, which is a good thing (Although it also removes YaST logo from there too ;c ).

Yes I can take care of spec :D

**Comment by lnussel** [comment]
you got the job :)

Also, https://github.com/openSUSE/installation-images needs to pull the new subpackage in

**Pull request merged**
