### PR TITLE
Run optipng over pngs

### PR DESCRIPTION
**Pull request by hellcp**

### CODE REVIEW

**Comment by sysrich** [comment]
The reason we stopped doing that in the past was a tendency for optipng to produce different enough pngs that openQA cared and so we kept on having to reneedle just because of a new build

If you are confident this won’t happen, LGTM

**Comment by hellcp** [comment]
The only part that is checked with openQA from this PR is GRUB, afaik Plymouth and Xfce splash are completely ignored.

**Comment by sysrich** [comment]
IIRC it was different in the olden times I am referring to.. 👴

**Comment by coolo** [comment]
It's the first time I hear that optipng changes pngs in a way that is visible at all. All it does is comparing different compression settings - if it changes the resulting pixels, it's a critical bug. Especially as openqa calls optipng on needles you create, it would be *very* problematic.

**Pull request merged**
