### PR TITLE
Set of new wallpapers for Leap 15.5 #132

### LINKED ISSUE #132: openSUSE Leap 15.5 wallpaper refresh
A tracker for the effort recently briefed on Community meeting https://etherpad.opensuse.org/p/weeklymeeting20211207
SUSE Branding team would help us to make wallpapers with SLES look and feel.

The topic of a new background was for the first time discussed I believe in 15.2, I think 15.4 based on SLES 15 SP4 which is a feature release could deliver such a welcome change to our desktop users.

Expectation is to have backgrounds in Leap 15.4 prior Feb 23rd which is the date when we'd like to have a Leap 15.4 Beta build done. https://en.opensuse.org/openSUSE:Roadmap

### PR DESCRIPTION
**Pull request by lkocman**
* Look and feel from SLES set of wallpaper
    * Bump makefile for 15.5
    * Resolves Issue #132 

comparison

ps. Arrows on the screenshot will not be part of the product :-)

### CODE REVIEW

**Comment by lkocman** [comment]
Alternative openSUSE project logo placement, to not have both logos on the right side.

logo_placement_change

**Comment by lkocman** [comment]
Should I create a development branch where all can push?

**Comment by hellcp** [comment]
We should have some guidelines about distribution logo positioning, it feels like the text is a tad too close to the logo itself.

**Comment by lkocman** [comment]
> We should have some guidelines about distribution logo positioning, it feels like the text is a tad too close to the logo itself.

what do you suggest for now? I can copy the SUSE's distance

**Comment by hellcp** [comment]
Logo_guidelines
This should apply to all of our distro logos, should make things easier for the future

**Comment by lkocman** [comment]
As I work I'm still in struggle if the yellow logo with white font would not be a better fit. @hellcp @ddemaio thoughts? This would also follow the trend from SUSE wallpaper where geeko is green and text is white.

Newly proposed variant:
desktop-1920x1080_logo_yellow
Old variant:
white

**Comment by lkocman** [comment]
Switching wallpapers over and over again I like the yellow/white better, looks more pro.

**Comment by lkocman** [comment]
Last commit with yellow logo can be optionally reverted, otherwise I'm pretty happy with the wallpaper set as it is now. All compatible aspect ratio are scaled version of each other etc.

**Comment by lkocman** [comment]
@ddemaio @hellcp final thoughts?

**Comment by ddemaio** [comment]
I'm good with it @lkocman. The yellow relates to get.o.o, so I think the color relation gives an association to that.

**Comment by hellcp** [comment]
I don't like the yellow, it doesn't tie to anything else on the wallpaper, there are blues, greens, white but no other yellow

**Comment by lkocman** [comment]
@hellcp my idea was that it's the only color representing current Leap. Rest of colors is project colors. I do agree that in SUSE's case the green can be find within bars.

**Comment by lkocman** [comment]
Thank you for your feedback @ddemaio @hellcp. I did revert my last commit (switch to yellow). I did adapt white logo to the branding guidelines from @hellcp in commit before switch to yellow. So we're all good.

**Comment by nilxam** [comment]
openqa result https://openqa.opensuse.org/tests/2656761#step/opensuse_welcome/4 , "Leap" doesn't correctly to be rendered next to the logo.

**Comment by hellcp** [comment]
Should probably have done Path -> Union over the text, so that it's a path and not a text layer

**Comment by lkocman** [comment]
Ah will do then! Thank you!

**Comment by simotek** [comment]
Only just saw this, if you wanted to move to a Yellow for 15.6 I think you'd have to change up the color palette a bit, but i'm sure that there is one that would work.

**Pull request merged**
